### ISSUE TITLE
taskqueue.add does not work with "GET" as the HTTP method

### ISSUE THREAD

**Issue by giacecco** [gmosx/appengine_js#1]
See http://groups.google.com/group/appenginejs/browse_thread/thread/62e94966d721fc2b/495eec2cc450ce57#495eec2cc450ce57 . If the task is defined with "GET" as a method, no tasks are added to the queue, nor any errors are returned. "POST" apparently works.

G.

**Comment by giacecco** [comment]
It was my mistake. If the method is GET and the URL in the task is wrong (one letter, in my case), the task manager immediately removes any trace of it the moment it is added to the queue. Hence, it looks like the task was not added to the queue. I wonder why the same doesn't happen for POST.

**Comment by gmosx** [comment]
so, should I close the task?

**Comment by giacecco** [comment]
I closed it already
