### ISSUE TITLE
Can't clone AppengineJS from GitHub

### ISSUE THREAD

**Issue by giacecco** [gmosx/appengine_js#2]
Wrong permissions or my fault? I usually don't have this problem... . I managed to download the whole directly from GitHub anyway.

Giaceccos-MacBook-Air:temp giacecco$ git clone git@github.com:gmosx/appengine.git
Cloning into appengine...
ERROR: Permission to gmosx/appengine denied to giacecco.
fatal: The remote end hung up unexpectedly
Giaceccos-MacBook-Air:temp giacecco$

**Comment by gmosx** [comment]
It would be better to clone the repo through github and work on you own version.
this way it is easier to send patches (pull requests)

**Comment by gtoast** [comment]
Seems to download fine if you just do:
 `git clone http://github.com/gmosx/appengine.git`

That git@github thing only works if you own or are an official contributor to a repo.

**Comment by giacecco** [comment]
All ok now, thanks
