### ISSUE TITLE
Can't save unicode strings into datastore TextProperty

### ISSUE THREAD

**Issue by giacecco** [gmosx/appengine_js#7]
How do I tell AppengineJS that the string I am going to save into a TextProperty field is unicode rather than ASCII? Every time I do, I later found the non-ASCII characters being replaced by garbage, represented by question marks in black diamonds when using the live GAE datastore viewer (see a screenshot of this at http://dl.dropbox.com/u/13837050/questionmarks.png ).

I understand than in Python it is quite easy for GAE's standard libraries to tell the difference between an ASCII and an unicode string (see for example http://stackoverflow.com/questions/2977701/google-datastore-blob-or-text ). What about with AppengineJS?

**Comment by gmosx** [comment]
TextProperty should handle UTF-8. Are you setting a String, ie:

myobj.myprop = "utf8 string";

or perhaps you are converting a Binary (you will have to use something like decodeToString("UTF8");

**Comment by giacecco** [comment]
My fault, as usual! I encoded the source text correctly on my debugging environment, I didn't live (the .decodeToString("UTF8") part). Sorry!
